name: Deploy Laravel to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: ./
          exclude: |
            **/.git*
            **/docker/**
            **/tests/**
            **/vendor/**
            .env
            .github/**

  vendor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Check composer changes
        id: check-composer
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "composer\.\(json\|lock\)"; then
            echo "composer_changed=true" >> $GITHUB_OUTPUT
          else
          echo "No composer changes detected, skipping vendor upload"
            echo "composer_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up PHP
        if: steps.check-composer.outputs.composer_changed == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, pdo, curl, xml, ctype, fileinfo, openssl, tokenizer, zip
          tools: composer

      - name: Install PHP dependencies
        if: steps.check-composer.outputs.composer_changed == 'true'
        run: |
          composer install --no-dev --optimize-autoloader
          cd vendor
          zip -r ../vendor.zip .
          cd ..

      - name: Upload vendor script
        if: steps.check-composer.outputs.composer_changed == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: ./vendor/
          exclude: |
            **/*
            !vendor.zip

  post-deploy:
    needs: [deploy, vendor]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate post-deploy script
        id: generate-post-deploy
        run: |
          AUTH_TOKEN=$(openssl rand -hex 32)
          mkdir -p public
          sed "s/{{TOKEN}}/$AUTH_TOKEN/g" .github/scripts/post-deploy.template.php > public/post-deploy.php
          echo "token=$AUTH_TOKEN" >> $GITHUB_OUTPUT

      - name: Upload post-deploy script
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: ./public/
          server-dir: ./public/
          exclude: |
            **/*
            !post-deploy.php

      - name: Execute post-deploy commands
        run: |
          curl -fsS \
            -H "User-Agent: GitHub Actions" \
            "${{ secrets.DEPLOY_URL }}/post-deploy.php?token=${{ steps.generate-post-deploy.outputs.token }}"